plugins {
    id 'com.android.library'
    id 'de.mannodermaus.android-junit5'
    id 'io.github.neboskreb.javaagent'
}

android {
    defaultConfig {
        minSdkVersion 36
        targetSdkVersion 36
        compileSdk = 36

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'io.github.neboskreb.javaagent.example.android.library'
}

dependencies {
    implementation libs.core.ktx

    testImplementation 'org.mockito:mockito-core:5.22.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.22.0'
    testJavaagent      'org.mockito:mockito-core:5.22.0'
    //region JUnit 6
    testImplementation platform('org.junit:junit-bom:6.0.2')
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'
    testRuntimeOnly    'org.junit.jupiter:junit-jupiter-engine'
    //endregion


    androidTestImplementation 'org.mockito:mockito-android:5.22.0'
    androidTestImplementation 'org.mockito:mockito-junit-jupiter:5.22.0'
    //region JUnit 6
    androidTestImplementation platform('org.junit:junit-bom:6.0.2')
    androidTestImplementation 'org.junit.jupiter:junit-jupiter-api'    //endregion
}
